arb-dir: lib/l10n
template-arb-file: intl_fi.arb  # Käytä suomea pohjana
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: [fi, sv]  # Lista tuetuista kielistä